parameters:
    week_vecations: 5,6
    week_vecations_overtime: 6
    max_checkin: 11:00

services:
#    page_admin:
#      class: Objects\AdminBundle\Admin\PageAdmin
#      tags:
#         - { name: sonata.admin, manager_type: orm, label: Page }
#      arguments: [null, Objects\AdminBundle\Entity\Page, SonataAdminBundle:CRUD]
#    block_admin:
#      class: Objects\AdminBundle\Admin\BlockAdmin
#      tags:
#         - { name: sonata.admin, manager_type: orm, label: Block }
#      arguments: [null, Objects\AdminBundle\Entity\Block, SonataAdminBundle:CRUD]
#    banner_admin:
#      class: Objects\AdminBundle\Admin\BannerAdmin
#      tags:
#         - { name: sonata.admin, manager_type: orm, label: Banner }
#      arguments: [null, Objects\AdminBundle\Entity\Banner, ObjectsAdminBundle:Banner]
    user_admin:
        class: Objects\AdminBundle\Admin\UserAdmin
        arguments: [~, Objects\UserBundle\Entity\User, ObjectsAdminBundle:User]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: User}

    department_admin:
        class: Objects\AdminBundle\Admin\DepartmentAdmin
        arguments: [~, Objects\AttendenceBundle\Entity\Department, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Department}

    position_admin:
        class: Objects\AdminBundle\Admin\PositionAdmin
        arguments: [~, Objects\AttendenceBundle\Entity\Position, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Position}

    vacation_cat_admin:
        class: Objects\AdminBundle\Admin\VacationCatAdmin
        arguments: [~, Objects\AttendenceBundle\Entity\VacationCat, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Vacation Category}

    vacation_admin:
        class: Objects\AdminBundle\Admin\VacationAdmin
        arguments: [~, Objects\AttendenceBundle\Entity\Vacation, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Vacation}

    employee_admin:
        class: Objects\AdminBundle\Admin\EmployeeAdmin
        arguments: [~, Objects\AttendenceBundle\Entity\Employee, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Employee}

    permission_admin:
        class: Objects\AdminBundle\Admin\PermissionAdmin
        arguments: [~, Objects\AttendenceBundle\Entity\Permission, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Permission}

    user_vacation_admin:
        class: Objects\AdminBundle\Admin\UserVacationAdmin
        arguments: [~, Objects\AttendenceBundle\Entity\UserVacation, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: User Vacation}

    attendence_admin:
        class: Objects\AdminBundle\Admin\AttendenceAdmin
        arguments: [~, Objects\AttendenceBundle\Entity\Attendence, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Attendence}
