<?php

namespace Objects\AttendenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttendenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendenceRepository extends EntityRepository {

    public function getAttendence($user_id, $startDate, $endDate) {
        $startDate = new \DateTime($startDate->format("Y-m-d 01:00:00"));
        $endDate = new \DateTime($endDate->format("Y-m-d 23:59:59"));
        return $this->getEntityManager()
                ->createQuery(
                        "SELECT a
                         FROM ObjectsAttendenceBundle:Attendence a
                         WHERE a.user = :user_id
                         AND a.checkin >= :startDate
                         AND a.checkout <= :endDate
                        "
                )->setParameters(array('user_id' => $user_id, 'startDate' => $startDate, 'endDate' => $endDate))
                ->getResult();
    }


    public function getAttendenceHours($user_id, $startDate, $endDate) {
        $startDate = new \DateTime($startDate->format("Y-m-d 01:00:00"));
        $endDate = new \DateTime($endDate->format("Y-m-d 23:59:59"));
        return $this->getEntityManager()
                ->createQuery(
                        "SELECT sum(a.total)
                         FROM ObjectsAttendenceBundle:Attendence a
                         WHERE a.user = :user_id
                         AND a.checkin >= :startDate
                         AND a.checkout <= :endDate
                        "
                )->setParameters(array('user_id' => $user_id, 'startDate' => $startDate, 'endDate' => $endDate))
                ->getResult();
    }

    public function isCheckedin($userId, $todayDate) {
        return $this->getEntityManager()
                ->createQuery(
                        "SELECT a
                         FROM ObjectsAttendenceBundle:Attendence a
                         WHERE a.user = :user_id
                         AND a.checkin >= :today
                        "
                )->setParameters(array('user_id' => $userId, 'today' => $todayDate))
                ->getResult();
    }

    public function isCheckedout($userId, $todayDate) {
        return $this->getEntityManager()
                ->createQuery(
                        "SELECT a
                         FROM ObjectsAttendenceBundle:Attendence a
                         WHERE a.user = :user_id
                         AND a.checkout >= :today
                        "
                )->setParameters(array('user_id' => $userId, 'today' => $todayDate))
                ->getResult();
    }

}
