<?php

namespace Objects\AttendenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserVacationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVacationRepository extends EntityRepository
{
    public function getUserVacationNumber($user_id, $startDate, $endDate) {
        $startDate = new \DateTime($startDate->format("Y-m-d 01:00:00"));
        $endDate = new \DateTime($endDate->format("Y-m-d 23:59:59"));
        return $this->getEntityManager()
                ->createQuery(
                        "SELECT sum(a.total)
                         FROM ObjectsAttendenceBundle:UserVacation a
                         WHERE (a.user = :user_id
                         OR a.user IS NULL)
                         AND a.startDate >= :startDate
                         AND a.endDate <= :endDate
                        "
                )->setParameters(array('user_id' => $user_id, 'startDate' => $startDate, 'endDate' => $endDate))
                ->getResult();
    }
}
