<?php

namespace Objects\AttendenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VacationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacationRepository extends EntityRepository
{
}
