<?php

namespace Objects\AttendenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VacationCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacationCatRepository extends EntityRepository
{
}
